### ISSUE TITLE
EateryAdapter in wrong package

### ISSUE THREAD

**Issue by CrazySwe** [mjovanc/easyfood#25]
Seems `EateryAdapter` is in wrong package of "Model" ?

**Comment by mjovanc** [comment]
@ohaganight What do you think about this? Should we move it to view package perhaps?

**Comment by ohaganight** [comment]
Yes, Move it to where it should be. Maybe in a adapter package i dess view package. customer/adapter ?

**Comment by seisser** [comment]
Flyttade den direkt till viewn. Men kanske borde läggas i nått subpackage som du skriver.
