### ISSUE TITLE
RecyclerView is not updating the view

### ISSUE THREAD

**Issue by ohaganight** [mjovanc/easyfood#26]
The view is not updated at once, meaning that the screen is not showing the list items in the recyclerview when the screen is shown. Right now you have to go back and forward to get the updated view.

**Comment by ohaganight** [comment]
I think that the problem might be in the view or/and viewmodel implementation.

**Comment by ohaganight** [comment]
I will take a look at this bug later today but feel free to dig into it.

**Comment by mjovanc** [comment]
Maybe consider using Fragments, if that may solve the issue?
